name: trainings_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  supabase_flutter: ^2.8.4
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.2.1
  email_validator: ^3.0.0
  sqflite: ^2.4.1
  path: ^1.9.0
  http: ^1.3.0
  gif: ^2.3.0
  fl_chart: ^0.71.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  flutter_staggered_animations: ^1.1.1

  test: ^1.24.0
  sqflite_common_ffi: ^2.3.4
  build_runner: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/initial_data/
    - .env
    - assets/img/
    - assets/ui/
    - assets/exercises/abs/
    - assets/exercises/arms/
    - assets/exercises/back/
    - assets/exercises/chest/
    - assets/exercises/legs/
    - assets/exercises/shoulders/
    - assets/exercises/stretching/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ui/logo.jpg"
